# Generated by Django 4.2.5 on 2023-09-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballTeam',
            fields=[
                ('team_registration_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20)),
                ('total_registered_players', models.IntegerField()),
            ],
        ),
    ]
