# Generated by Django 4.2.5 on 2023-09-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GolfPlayer',
            fields=[
                ('player_registration_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=20)),
                ('player_surname', models.CharField(max_length=20)),
                ('player_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RugbyTeam',
            fields=[
                ('team_registration_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=20)),
                ('total_registered_players', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TennisPlayer',
            fields=[
                ('player_registration_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=20)),
                ('player_surname', models.CharField(max_length=20)),
                ('player_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackAthlete',
            fields=[
                ('player_registration_key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=20)),
                ('player_surname', models.CharField(max_length=20)),
                ('player_age', models.IntegerField()),
            ],
        ),
    ]
