version: '3'

services:

  web:
    image: python:3.11
    container_name: my_project
    command: bash -c "sleep 5 && cd my_project && pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./my_project:/my_project
    ports:
      - "8000:8000"
    depends_on:
      - db

  web2:
    image: armandleroux/django_proj:django_test
    container_name: another_service
    command: python manage.py runserver 0.0.0.0:8001
    ports:
    - "8001:8001"

  db:
    image: postgres:13
    container_name: postgresql_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e4r
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: -p 5432

volumes:
  pgdata:
