version: '3.9'

services:
  web:
    build: ./django_proj
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: my_service
    volumes:
      - ./django_proj:/my_service
    ports:
      - "8000:8000"